### ISSUE TITLE
interoperability with PyCBC

### ISSUE THREAD

**Issue by ahnitz** [sxs-collaboration/gwsurrogate#22]
I'm interested in adding support so that gwsurrogate has better interoperability with the PyCBC gw data analysis package. The primary case here would be that gwsurrogate is able to act as a source of waveform models for our generic python GW waveform interface, and by doing so, be available for use as templates or injections for both parameter estimation and searches (or just make use in notebooks easier with a common interface). 

A while back we added a plugin interface which should allow gwsurrogate to advertise what waveforms it can provide and harmonize the interface. For an example of what interface code is needed, see the reference example plugin. 
https://github.com/gwastro/example-waveform-plugin

To be clear, this requires no explicit dependency on PyCBC, but would mean that if you have both packages installed ala

```
pip install gwsurrogate pycbc
```

that PyCBC programs and functions would immediately be aware of the waveforms from gwsurrogate and be able to use them.

I am willing to put together a PR. The changes would be limited a new module that contains the interface functions and small additions to setup.py so that gwsurrogate advertises globally its capabilities. 

What do gwsurrogate developers think?

**Comment by duetosymmetry** [comment]
The main questions I think of here are: Should `gwsurrogate` advertise only one `entry_point`, with a parameter that specifies which surrogate model is used; or if there should be one `entry_point` for each model? Does this depend on the API that `pycbc` expects of a plugin?

**Comment by ahnitz** [comment]
@duetosymmetry In principle it can be done either way with no loss in functionality. My preference would have been however to advertise each model separately as that is more similar to how it is done for other waveform sources. (each entry point corresponds to the 'approximant' keyword for our waveform generation).
