### ISSUE TITLE
ERROR using SimpleH5Object._read_subordinates

### ISSUE THREAD

**Issue by seth-olsen** [sxs-collaboration/gwsurrogate#4]
I have been using NRHybSur3dq8 with gwsurrogate version 0.9.9 for several months on a Python 3.7 conda environment, and that environment is unable to install pymultinest because of conflicts with lots of parallelization libraries (mpi, mpich2, openmp, and many more), so I'm trying to make a new environment that can use both gwsurrogate and pymultinest.

In trying to use gwsurrogate.LoadSurrogate('NRHybSur3dq8') with a new environment,
I'm getting an error from the file "gwsurrogate/new/saveH5Object.py"
attempting to use SimpleH5Object._read_h5
ERROR MESSAGE:
/home/seth/anaconda3/envs/gw/lib/python3.8/site-packages/gwsurrogate/new/saveH5Object.py:106: H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
  v = item.value
Traceback (most recent call last):
  File "/home/seth/anaconda3/envs/gw/lib/python3.8/site-packages/gwsurrogate/new/saveH5Object.py", line 205, in _read_subordinates
    getattr(self, k)._read_h5(f[k])
  File "/home/seth/anaconda3/envs/gw/lib/python3.8/site-packages/gwsurrogate/new/saveH5Object.py", line 192, in _read_h5
    self.h5_prepare_subs()
  File "/home/seth/anaconda3/envs/gw/lib/python3.8/site-packages/gwsurrogate/new/nodeFunction.py", line 94, in h5_prepare_subs
    self.fitFunc = evaluate_fit.getFitEvaluator(self.fit_data)
  File "/home/seth/anaconda3/envs/gw/lib/python3.8/site-packages/gwsurrogate/eval_pysur/evaluate_fit.py", line 252, in getFitEvaluator
    gpr_predictObject = GPRPredictor(res)
  File "/home/seth/anaconda3/envs/gw/lib/python3.8/site-packages/gwsurrogate/eval_pysur/evaluate_fit.py", line 39, in __init__
    if not StrictVersion(sklearn.__version__) >= StrictVersion('0.19.1'):
  File "/home/seth/anaconda3/envs/gw/lib/python3.8/distutils/version.py", line 40, in __init__
    self.parse(vstring)
  File "/home/seth/anaconda3/envs/gw/lib/python3.8/distutils/version.py", line 137, in parse
    raise ValueError("invalid version number '%s'" % vstring)
ValueError: invalid version number '0.22.2.post1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/seth/anaconda3/envs/gw/lib/python3.8/site-packages/gwsurrogate/new/saveH5Object.py", line 205, in _read_subordinates
    getattr(self, k)._read_h5(f[k])
  File "/home/seth/anaconda3/envs/gw/lib/python3.8/site-packages/gwsurrogate/new/saveH5Object.py", line 233, in _read_h5
    self.object_list[i]._read_h5(g)
  File "/home/seth/anaconda3/envs/gw/lib/python3.8/site-packages/gwsurrogate/new/saveH5Object.py", line 193, in _read_h5
    self._read_subordinates(f)
  File "/home/seth/anaconda3/envs/gw/lib/python3.8/site-packages/gwsurrogate/new/saveH5Object.py", line 207, in _read_subordinates
    raise Exception("%s could not be read: %s"%(k, e))
Exception: node_function could not be read: invalid version number '0.22.2.post1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/seth/anaconda3/envs/gw/lib/python3.8/site-packages/gwsurrogate/new/saveH5Object.py", line 205, in _read_subordinates
    getattr(self, k)._read_h5(f[k])
  File "/home/seth/anaconda3/envs/gw/lib/python3.8/site-packages/gwsurrogate/new/saveH5Object.py", line 277, in _read_h5
    v._read_h5(f[_list_item_string(idx)])
  File "/home/seth/anaconda3/envs/gw/lib/python3.8/site-packages/gwsurrogate/new/saveH5Object.py", line 193, in _read_h5
    self._read_subordinates(f)
  File "/home/seth/anaconda3/envs/gw/lib/python3.8/site-packages/gwsurrogate/new/saveH5Object.py", line 207, in _read_subordinates
    raise Exception("%s could not be read: %s"%(k, e))
Exception: node_functions could not be read: node_function could not be read: invalid version number '0.22.2.post1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/seth/anaconda3/envs/gw/lib/python3.8/site-packages/gwsurrogate/new/saveH5Object.py", line 205, in _read_subordinates
    getattr(self, k)._read_h5(f[k])
  File "/home/seth/anaconda3/envs/gw/lib/python3.8/site-packages/gwsurrogate/new/saveH5Object.py", line 277, in _read_h5
    v._read_h5(f[_list_item_string(idx)])
  File "/home/seth/anaconda3/envs/gw/lib/python3.8/site-packages/gwsurrogate/new/saveH5Object.py", line 193, in _read_h5
    self._read_subordinates(f)
  File "/home/seth/anaconda3/envs/gw/lib/python3.8/site-packages/gwsurrogate/new/saveH5Object.py", line 207, in _read_subordinates
    raise Exception("%s could not be read: %s"%(k, e))
Exception: func_subs could not be read: node_functions could not be read: node_function could not be read: invalid version number '0.22.2.post1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/seth/research/gw_detection_home/multimode_waveform_generator.py", line 39, in <module>
    SUR_HYB = gwsurrogate.LoadSurrogate('NRHybSur3dq8') # non-precessing hybrid surrogate model
  File "/home/seth/anaconda3/envs/gw/lib/python3.8/site-packages/gwsurrogate/surrogate.py", line 2235, in __new__
    return SURROGATE_CLASSES[surrogate_name](surrogate_h5file)
  File "/home/seth/anaconda3/envs/gw/lib/python3.8/site-packages/gwsurrogate/surrogate.py", line 1963, in __init__
    super(NRHybSur3dq8, self).__init__(self.__class__.__name__, \
  File "/home/seth/anaconda3/envs/gw/lib/python3.8/site-packages/gwsurrogate/surrogate.py", line 1376, in __init__
    self._sur_dimless = self._load_dimless_surrogate()
  File "/home/seth/anaconda3/envs/gw/lib/python3.8/site-packages/gwsurrogate/surrogate.py", line 1979, in _load_dimless_surrogate
    sur.load(self.h5filename)
  File "/home/seth/anaconda3/envs/gw/lib/python3.8/site-packages/gwsurrogate/new/saveH5Object.py", line 148, in load
    self._read_h5(f)
  File "/home/seth/anaconda3/envs/gw/lib/python3.8/site-packages/gwsurrogate/new/saveH5Object.py", line 193, in _read_h5
    self._read_subordinates(f)
  File "/home/seth/anaconda3/envs/gw/lib/python3.8/site-packages/gwsurrogate/new/saveH5Object.py", line 207, in _read_subordinates
    raise Exception("%s could not be read: %s"%(k, e))
Exception: sur_subs could not be read: func_subs could not be read: node_functions could not be read: node_function could not be read: invalid version number '0.22.2.post1'
END ERROR MESSAGE

I have tried installing the dependencies in many different orders in new conda environments, but this same error keeps occurring. I have also tried updating conda and all packages. I have also tried initializing the environment with all the packages at once, but it gives me the following conflict error message:

[conda_newenv_output.txt](https://github.com/sxs-collaboration/gwsurrogate/files/4547627/conda_newenv_output.txt)

**Comment by seth-olsen** [comment]
I've also tried setting python=3.7 and gwsurrogate=0.9.9, in which case I can create the environment with 
conda create --name gw numpy scipy matplotlib jupyter pymultinest gsl h5py hdf5 fftw numba pandas multiprocess lal lalsimulation gwtools gwsurrogate
(NOTE: lalapps causes unresolvable conflicts)

but then I get the same error copied at the beginning of the original post when I try to load NRHybSur3dq8

**Comment by vijayvarma392** [comment]
Hi Seth, can you try the lastest version of gwsurrogate: https://pypi.org/project/gwsurrogate/.
The check `if not StrictVersion(sklearn.version) >= StrictVersion('0.19.1'):` has now been removed.

**Comment by seth-olsen** [comment]
Hi Vijay, thanks for the quick response! Here is the list of packages I'm installing in the environment:

conda create --name gw numpy scipy matplotlib scikit-learn notebook gsl h5py hdf5 fftw numba pandas pymultinest multiprocess lal lalsimulation gwtools gwsurrogate

and I'm now able to install all of these current versions together without conflicts, but when I try to load NRHybSur3dq8 I'm still getting the same error:

/home/seth/anaconda3/envs/gw/lib/python3.8/site-packages/gwsurrogate/new/saveH5Object.py:106: H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
  v = item.value

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/anaconda3/envs/gw/lib/python3.8/site-packages/gwsurrogate/new/saveH5Object.py in _read_subordinates(self, f)
    204             try:
--> 205                 getattr(self, k)._read_h5(f[k])
    206             except Exception as e:

~/anaconda3/envs/gw/lib/python3.8/site-packages/gwsurrogate/new/saveH5Object.py in _read_h5(self, f)
    191         self._read_data(f, keys)
--> 192         self.h5_prepare_subs()
    193         self._read_subordinates(f)

~/anaconda3/envs/gw/lib/python3.8/site-packages/gwsurrogate/new/nodeFunction.py in h5_prepare_subs(self)
     93     def h5_prepare_subs(self):
---> 94         self.fitFunc = evaluate_fit.getFitEvaluator(self.fit_data)
     95 

~/anaconda3/envs/gw/lib/python3.8/site-packages/gwsurrogate/eval_pysur/evaluate_fit.py in getFitEvaluator(res)
    251     if 'fitType' in res and res['fitType'] == 'GPR':
--> 252         gpr_predictObject = GPRPredictor(res)
    253         return gprfitEvaluator

~/anaconda3/envs/gw/lib/python3.8/site-packages/gwsurrogate/eval_pysur/evaluate_fit.py in __init__(self, res, **kwargs)
     38         import sklearn
---> 39         if not StrictVersion(sklearn.__version__) >= StrictVersion('0.19.1'):
     40             raise Exception('sklearn needs to be at least version 0.19.1. See '

~/anaconda3/envs/gw/lib/python3.8/distutils/version.py in __init__(self, vstring)
     39         if vstring:
---> 40             self.parse(vstring)
     41 

~/anaconda3/envs/gw/lib/python3.8/distutils/version.py in parse(self, vstring)
    136         if not match:
--> 137             raise ValueError("invalid version number '%s'" % vstring)
    138 

ValueError: invalid version number '0.22.2.post1'

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
~/anaconda3/envs/gw/lib/python3.8/site-packages/gwsurrogate/new/saveH5Object.py in _read_subordinates(self, f)
    204             try:
--> 205                 getattr(self, k)._read_h5(f[k])
    206             except Exception as e:

~/anaconda3/envs/gw/lib/python3.8/site-packages/gwsurrogate/new/saveH5Object.py in _read_h5(self, f)
    232             g = f[_list_item_string(i)]
--> 233             self.object_list[i]._read_h5(g)
    234 

~/anaconda3/envs/gw/lib/python3.8/site-packages/gwsurrogate/new/saveH5Object.py in _read_h5(self, f)
    192         self.h5_prepare_subs()
--> 193         self._read_subordinates(f)
    194 

~/anaconda3/envs/gw/lib/python3.8/site-packages/gwsurrogate/new/saveH5Object.py in _read_subordinates(self, f)
    206             except Exception as e:
--> 207                 raise Exception("%s could not be read: %s"%(k, e))
    208 

Exception: node_function could not be read: invalid version number '0.22.2.post1'

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
~/anaconda3/envs/gw/lib/python3.8/site-packages/gwsurrogate/new/saveH5Object.py in _read_subordinates(self, f)
    204             try:
--> 205                 getattr(self, k)._read_h5(f[k])
    206             except Exception as e:

~/anaconda3/envs/gw/lib/python3.8/site-packages/gwsurrogate/new/saveH5Object.py in _read_h5(self, f)
    276             idx = keys.index(k)
--> 277             v._read_h5(f[_list_item_string(idx)])
    278 

~/anaconda3/envs/gw/lib/python3.8/site-packages/gwsurrogate/new/saveH5Object.py in _read_h5(self, f)
    192         self.h5_prepare_subs()
--> 193         self._read_subordinates(f)
    194 

~/anaconda3/envs/gw/lib/python3.8/site-packages/gwsurrogate/new/saveH5Object.py in _read_subordinates(self, f)
    206             except Exception as e:
--> 207                 raise Exception("%s could not be read: %s"%(k, e))
    208 

Exception: node_functions could not be read: node_function could not be read: invalid version number '0.22.2.post1'

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
~/anaconda3/envs/gw/lib/python3.8/site-packages/gwsurrogate/new/saveH5Object.py in _read_subordinates(self, f)
    204             try:
--> 205                 getattr(self, k)._read_h5(f[k])
    206             except Exception as e:

~/anaconda3/envs/gw/lib/python3.8/site-packages/gwsurrogate/new/saveH5Object.py in _read_h5(self, f)
    276             idx = keys.index(k)
--> 277             v._read_h5(f[_list_item_string(idx)])
    278 

~/anaconda3/envs/gw/lib/python3.8/site-packages/gwsurrogate/new/saveH5Object.py in _read_h5(self, f)
    192         self.h5_prepare_subs()
--> 193         self._read_subordinates(f)
    194 

~/anaconda3/envs/gw/lib/python3.8/site-packages/gwsurrogate/new/saveH5Object.py in _read_subordinates(self, f)
    206             except Exception as e:
--> 207                 raise Exception("%s could not be read: %s"%(k, e))
    208 

Exception: func_subs could not be read: node_functions could not be read: node_function could not be read: invalid version number '0.22.2.post1'

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
<ipython-input-4-95507ddf6842> in <module>
----> 1 import multimode_waveform_generator as mmwf
      2 import multimode_template_bank_generator as mmtg

~/research/gw_detection_home/multimode_waveform_generator.py in <module>
     37 import gwsurrogate
     38 #sur_pre = gwsurrogate.LoadSurrogate('NRSur7dq4') # precessing surrogate model
---> 39 SUR_HYB = gwsurrogate.LoadSurrogate('NRHybSur3dq8') # non-precessing hybrid surrogate model
     40 SUR_HYB_CONST_KWS = {'units':'mks', 'dist_mpc':1, 'skip_param_checks':True, \
     41                      'f_ref':None, 'df':None, 'freqs':None, 'times':None, 'ellMax':None, \

~/anaconda3/envs/gw/lib/python3.8/site-packages/gwsurrogate/surrogate.py in __new__(self, surrogate_name, surrogate_name_spliced)
   2233             raise Exception('Invalid surrogate : %s'%surrogate_name)
   2234         else:
-> 2235             return SURROGATE_CLASSES[surrogate_name](surrogate_h5file)
   2236 

~/anaconda3/envs/gw/lib/python3.8/site-packages/gwsurrogate/surrogate.py in __init__(self, h5filename)
   1961         soft_param_lims = [8.01, 0.801]
   1962         hard_param_lims = [10.01, 1]
-> 1963         super(NRHybSur3dq8, self).__init__(self.__class__.__name__, \
   1964             domain_type, keywords, soft_param_lims, hard_param_lims)
   1965 

~/anaconda3/envs/gw/lib/python3.8/site-packages/gwsurrogate/surrogate.py in __init__(self, name, domain_type, keywords, soft_param_lims, hard_param_lims)
   1374 
   1375         # load the dimensionless surrogate
-> 1376         self._sur_dimless = self._load_dimless_surrogate()
   1377 
   1378         self._domain_type = domain_type

~/anaconda3/envs/gw/lib/python3.8/site-packages/gwsurrogate/surrogate.py in _load_dimless_surrogate(self)
   1977         """
   1978         sur = new_surrogate.AlignedSpinCoOrbitalFrameSurrogate()
-> 1979         sur.load(self.h5filename)
   1980         return sur
   1981 

~/anaconda3/envs/gw/lib/python3.8/site-packages/gwsurrogate/new/saveH5Object.py in load(self, filename)
    146         """Load data from h5 file"""
    147         with h5py.File(filename, 'r') as f:
--> 148             self._read_h5(f)
    149 
    150     def _default_data_keys(self):

~/anaconda3/envs/gw/lib/python3.8/site-packages/gwsurrogate/new/saveH5Object.py in _read_h5(self, f)
    191         self._read_data(f, keys)
    192         self.h5_prepare_subs()
--> 193         self._read_subordinates(f)
    194 
    195     def _read_data(self, f, keys):

~/anaconda3/envs/gw/lib/python3.8/site-packages/gwsurrogate/new/saveH5Object.py in _read_subordinates(self, f)
    205                 getattr(self, k)._read_h5(f[k])
    206             except Exception as e:
--> 207                 raise Exception("%s could not be read: %s"%(k, e))
    208 
    209 

Exception: sur_subs could not be read: func_subs could not be read: node_functions could not be read: node_function could not be read: invalid version number '0.22.2.post1'

**Comment by seth-olsen** [comment]
I've now made a new environment that forces scikit-learn=0.19.1 and I'm able to load the surrogate!

I've checked the source code file and the version on conda still has this in evaluate_fit.py:

class GPRPredictor:
    def __init__(self, res, **kwargs):
        """
        Class to evaluate GPR fits constructed by GPRFitter class in
        pySurrogate/fit_gpr.py
        """

        # 6/2018: keeping this test at class-level scope since the
        # bleeding-edge sklearn package isn't needed for the other models.
        # In the future, this check can be removed entirely
        from distutils.version import StrictVersion
        import sklearn
        if not StrictVersion(sklearn.__version__) >= StrictVersion('0.19.1'):
            raise Exception('sklearn needs to be at least version 0.19.1. See '
                'http://scikit-learn.org/stable/install.html for instructions.')

**Comment by vijayvarma392** [comment]
I see, I think that just means that the pypi changes have not propagated to conda-forge yet. @sfield17 is this not done automatically?

**Comment by duetosymmetry** [comment]
@vijayvarma392 it's updated automatically thanks to [this feedstock](https://github.com/conda-forge/gwsurrogate-feedstock) set up by @duncanmacleod. If you need to change the build reqs for that recipe, you'll need to open a PR on the feedstock repo, because the regro-cf-autotick-bot won't necessarily pick up those changes.

**Comment by vijayvarma392** [comment]
@duetosymmetry: I don't the build requirements changed, it is just a change in eval_pysur, which I believe is in the pip version.

**Comment by sfield17** [comment]
@seth-olsen: we just created a new version 1.0.3 that might fix the issue. Can you let us know if this new version fixes your problem?

**Comment by seth-olsen** [comment]
@sfield17: I've tried to use the new version, and I can install it with conda using

conda create --name ligo numpy scipy matplotlib scikit-learn notebook gsl h5py hdf5 fftw numba pandas pymultinest multiprocess lal lalsimulation gwtools gwsurrogate

but then I get the same python error when trying to load the surrogate (after successful catalog pulls):

[conda-error.txt](https://github.com/sxs-collaboration/gwsurrogate/files/4557451/conda-error.txt)

Also, if I try to keep the scikit-learn version unspecified but create the conda environment without gwsurrogate:

conda create --name ligo2 numpy scipy matplotlib scikit-learn notebook gsl h5py hdf5 fftw numba pandas pymultinest multiprocess lal lalsimulation gwtools

and then install with pip:

conda activate ligo2
pip install gwsurrogate

gwsurrogate won't install due to the following error

[pip-error.txt](https://github.com/sxs-collaboration/gwsurrogate/files/4557461/pip-error.txt)

then if I setup the conda environment again without gwsurrogate but now forcing the sklearn version:

conda create --name ligo3 numpy scipy matplotlib scikit-learn=0.19.1 notebook gsl h5py hdf5 fftw numba pandas pymultinest multiprocess lal lalsimulation gwtools

I get the exact same error when trying to install using pip (even though forcing this scikit-learn version and including gwsurrogate in the initial conda environment creation allows me to use NRHybSur3dq8 without issue)

I also tried manually adding the path /seth/anaconda3/envs/ligo3/include/ to my PATH variable in response to the pip install error, because that is the folder where the local gsl/gsl_spline.h lives, and pip install still gives the same error

NOTE: all the successful cases require both that scikit-learn=0.19.1 in the conda environment and that gwsurrogate is installed using conda, and in all such cases (i.e., using gwsurrogate versions 0.9.9, 1.0.2, or 1.0.3) I get the warning following warning when successfully loading the surrogate:
/home/seth/anaconda3/envs/ligo4/lib/python3.6/site-packages/gwsurrogate/new/saveH5Object.py:106: H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.

I'm not sure if this warning is relevent, but the whole reason I've been trying to reinstall in a new environment is that in my original environment with gwsurrogate=0.9.9 I am unable to install pymultinest because of persistent conflicts in packages involving hdf5 file handling and parallelization (although my testing has shown that this is likely due to my original conda environment having lalapps installed)

**Comment by sfield17** [comment]
@seth-olsen Just to double-check, the error you are referring to is the scipy version error where the relevant piece of output related to the gwsurrogate code is

```
File "/home/seth/anaconda3/envs/ligo/lib/python3.8/site-packages/gwsurrogate/eval_pysur/evaluate_fit.py", line 39, in __init__
    if not StrictVersion(sklearn.__version__) >= StrictVersion('0.19.1'):
```

If thats the case, can you please double-check this is for version 1.0.3? The reason is that for version [1.0.3 on pypi](https://files.pythonhosted.org/packages/50/b4/92b23626f745d603ce750d27b5f3e5c3ea8bd22d4ea000b3a367b10b4baf/gwsurrogate-1.0.3.tar.gz), the problematic line 39 shown above no longer exists in the evaluate_fit.py file. So I wonder if maybe some other gws installation is accidentally being imported instead? You can check by doing

```
>>> gwsurrogate.__version__
>>> gwsurrogate.__path__
```

after importing. 

regarding the installation problem with gsl header files: if you don't have gsl installed in a standard location (ie one that gcc would think to look in) you might need to modify your env variable C_INCLUDE_PATH to point to the folder containing gsl/gsl_spline.h. For example,  on our local cluster, I've needed to do this before trying to install gwsurrogate:

```
export C_INCLUDE_PATH=/home/sfield/anaconda3/envs/py27-test/include/gsl/
```

**Comment by seth-olsen** [comment]
@sfield17 you're right that it's not 1.0.3! even though pip has 1.0.3, conda only had 1.0.2 available (trying to force 1.0.3 in conda gives PackagesNotFoundError for the conda-forge repo that has the older versions)

so in order to test with 1.0.3 I will need to be able to get it from pip, but I've tried setting the include path with
export C_INCLUDE_PATH=/home/seth/anaconda3/envs/ligo3/include/gsl/
as well as setting the same value for CPATH, OBJC_INCLUDE_PATH, and CPLUS_INCLUDE_PATH, but none of that made the pip installation to go through

no matter how many of those environmental variables I set, I get the same error from the pip install, with all the calls to gcc using
-I/home/seth/anaconda3/envs/ligo3/include/python3.8
instead of the include path that I set

I've also tried setting 1 or all of those environment variables in the base environment and in my non-conda bash shell and then opening another terminal in the ligo3 env and trying the installation, but the same error results 
(ligo3 created with 
conda create --name ligo3 numpy scipy matplotlib scikit-learn notebook gsl h5py hdf5 fftw numba pandas pymultinest multiprocess lal lalsimulation gwtools)

**Comment by duetosymmetry** [comment]
@seth-olsen the PyPI update hasn't been accepted into conda-forge yet. @sfield17 or @vijayvarma392 can accept [this PR](https://github.com/conda-forge/gwsurrogate-feedstock/pull/8), then it will appear on conda-forge soon.

**Comment by sfield17** [comment]
Thanks for the reminder @duetosymmetry -- I always forget this extra step. @seth-olsen I've just accepted the PR so it should be on condo-forge.

regarding gsl: I've found that I need to install gsl first, and your gsl installation must be the development version that includes header files like gsl_spline.h. Then, as a second step, you can install gwsurrogate after setting the env variable C_INCLUDE_PATH. If gwsurrogate still complains about a missing gsl/gsl_spline.h file, please double-check that there is a file gsl_spline.h located in the directory pointed to by C_INCLUDE_PATH (either this path should point to gsl/gsl_spline.h or gsl_spline.h .. I forget which one works, but try both!)

Good luck! Let us know how it goes.

**Comment by seth-olsen** [comment]
gwsurrogate version 1.0.3 is now up on conda-forge and the install worked fine without any specification of the scikit-learn version! I still can't get pip to add anything to the include path (using C_INCLUDE_PATH or CPATH), so even though I've installed the right gsl, pip just can't find the directory. So pip doesn't work for me but the conda version is all good to go. Thanks so much for all the help!
