### ISSUE TITLE
BUG: NRSur7dq4 replacing f_low != 0 with f_ref 

### ISSUE THREAD

**Issue by seth-olsen** [sxs-collaboration/gwsurrogate#8]
SETUP:
sur = gwsurrogate.LoadSurrogate('NRSur7dq4')
t, wfdic, _ = sur(m1/m2, chi1, chi2, M=m1+m2, \
                         dt=my_dt, f_low=my_f_low, f_ref=my_f_ref, units='mks', \
                         inclination=None, phi_ref=None)
true_f_low = instantaneous_frequency(wfdic[(2, 2)], time_index=0)

t_0, wfdic_0, _ = sur(m1/m2, chi1, chi2, M=m1+m2, \
                                dt=my_dt, f_low=0, f_ref=None, units='mks', \
                                inclination=None, phi_ref=None)
min_f_low = instantaneous_frequency(wfdic_0[(2, 2)], time_index=0)
min_f_ref = min_f_low

WHAT WORKS:
-->  for  my_f_ref = None & my_f_low = 0,   f_ref & f_low inherit the value of min_f_low 
-->  for  my_f_ref = None & my_f_low > 0,   f_ref inherits the value of my_f_low
-->  for  any  my_f_ref != None,  f_ref keeps the value of my_f_ref
-->  for  any  my_f_ref > min_f_ref,  my_f_low = 0  ==>  t = t_0
(i.e., setting a value for f_ref does not affect the length of the returned waveform when f_low=0)
-->  for any  my_f_ref < min_f_ref,  sur() throws Exception: got omega_ref = ... too small!
(regardless of my_f_low, as intended)

WHAT IS BROKEN:
-->  for fixed my_f_ref > min_f_ref,  
  any  my_f_low > 0  results in the same t & true_f_low
-->  for different my_f_ref > min_f_ref,
  fixed  my_f_low > 0  results in different t & true_f_low
(for any fixed my_f_low -- can be > or < my_f_ref and/or min_f_low)

this indicates that for any my_f_ref != None and my_f_low > 0, 
the internal f_low is set to my_f_ref rather than my_f_low

that is, my_f_low=0 indeed sets the internal f_low to min_f_low and the internal f_ref
is set to my_f_ref != None (or it inherits the internal f_low when my_f_ref=None), BUT
whenever my_f_low != 0, the internal f_low looks first to see if you have passed
my_f_ref != None and inherits that value instead of my_f_low

I think this was probably implemented purposely as a guard against
throwing exceptions for 0 < my_f_low < min_f_low if the user has also passed
my_f_ref > min_f_low, because it makes sense for the internal f_low to inherit my_f_ref
in that case

however, this can result in a nasty analysis bug in the following example:

you want to set f_ref = 50 Hz to make the reference frames line up with results from a different
waveform model; and, in order to get consistent results over some region of physical parameter
space, you want to make sure that you only count SNR starting at the frequency of the 
maximal min_f_low that is forced by the surrogate's length constraints over that region of 
(q, chi1, chi2) -- maybe there are plenty of parameter combinations for which the surrogate
has min_f_low = 20 Hz, but there are also some parameters for which the best the model
can do is min_f_low = 30 Hz; so you set my_f_low = 30 and my_f_ref = 50, and  then
you unknowingly lose all the SNR from 30 Hz to 50 Hz

I know that the documentation recommends using f_low=0 for NRSur7dq4, 
and i'm not saying that the model needs to accommodate this scenario of 
setting my_f_ref != None and my_f_low != 0,  i'm just saying that if my_f_ref != None 
is going to behave this way then the documentation needs to be changed

also, if the behavior is actually unintended then it could be resulting in other silent bugs

**Comment by vijayvarma392** [comment]
@seth-olsen: This issue should now be fixed in gwsurrogate 1.0.5.
